name: Build artifacts
on:
  workflow_dispatch:
  schedule:
    - cron: "18 3 * * *"

jobs:
  check-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Remove obsolete releases
        run: |
          git config --local user.name "Github automations"
          git config --local user.email "{ID}+{username}@users.noreply.github.com"
          for ebuild in $(find | grep -e "home-assistant-frontend.*-node_modules\.tar\.xz$"); do
            version=$(echo $ebuild | rev | cut -d- -f2 | rev)
            if [ "$( curl -o /dev/null -s -w "%{http_code}\n" https://github.com/xavierforestier/HomeAssistantRepository/raw/refs/heads/master/dev-python/home-assistant-frontend/home-assistant-frontend-${version}.ebuild )" = "404" ]; then
              git rm "home-assistant-frontend-${version}-nodes_modules.tar.xz" || true
              git rm "home-assistant-frontend-${version}-translations.tar.xz" || true
              git commit -m "[CI]Drop obsolete release ${version}" || true
            fi
          done
          git push
          
      - name: Check last releases
        env:
          HA_TOKEN: ${{ secrets.HA_FRONTEND_TOKEN }}
        run: |
          git config --local user.name "Github automations"
          git config --local user.email "{ID}+{username}@users.noreply.github.com"
          for rel in $( curl  -H "Accept: application/vnd.github+json" -s https://api.github.com/repos/xavierforestier/HomeAssistantRepository/contents/dev-python/home-assistant-frontend | jq -r '.[] | select(.name | test(".*\\.ebuild$") ) | .name' ); do
            version=$( echo $rel | cut -d- -f4 | rev | cut -d. -f2- | rev)
            if [ ! -f "home-assistant-frontend-${version}-node_modules.tar.xz" ]; then
              mkdir /tmp/frontend-${version}
              pushd /tmp/frontend-${version}
              git clone https://github.com/home-assistant/frontend.git
              cd frontend/script
              git branch ${version}
              git pull
              ./setup
              cd ..
              curl  -Ls  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${HA_TOKEN}"  $( curl  -H "Accept: application/vnd.github+json" -s https://api.github.com/repos/home-assistant/frontend/actions/artifacts?name=translations | jq -r '.artifacts[0].archive_download_url' ) -o translations.zip
              rm translations.tar.gz || true
              unzip translations.zip && rm translations.zip
              tar -xvf translations.tar.gz
              cd ..
              mv frontend "frontend-${version}"
              XZ_OPT=-9 tar -Jcvf /tmp/home-assistant-frontend-${version}-node_modules.tar.xz frontend-${version}/node_modules/
              XZ_OPT=-9 tar -Jcvf /tmp/home-assistant-frontend-${version}-translations.tar.xz frontend-${version}/translations/
              popd
              mv /tmp/home-assistant-frontend-${version}-node_modules.tar.xz .
              rm -rf /tmp/frontend-${version}
              git add home-assistant-frontend-${version}-node_modules.tar.xz
              git add home-assistant-frontend-${version}-translations.tar.xz
              git commit -m "[CI]New release ${version}" || true
            fi
          done
          git push
