name: Fetch translations
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - env:
          HA_TOKEN: ${{ secrets.HA_FRONTEND_TOKEN }}
        name: Fetch last translation
        run: |
          curl  -Ls  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${HA_TOKEN}"  $( curl  -H "Accept: application/vnd.github+json" -s https://api.github.com/repos/home-assistant/frontend/actions/artifacts?name=translations | jq -r '.artifacts[0].archive_download_url' ) -o translation.zip
          unzip translation.zip && rm translation.zip
          ls -l
