name: Fetch translations
on:
  workflow_dispatch:
  schedule:
    - cron: "18 3 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - env:
          HA_TOKEN: ${{ secrets.HA_FRONTEND_TOKEN }}
        name: Fetch last translation
        run: |
          curl  -Ls  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${HA_TOKEN}"  $( curl  -H "Accept: application/vnd.github+json" -s https://api.github.com/repos/home-assistant/frontend/actions/artifacts?name=translations | jq -r '.artifacts[0].archive_download_url' ) -o translations.zip
          rm translations.tar.gz || true
          unzip translations.zip && rm translations.zip
          git config --local user.name "Github automations"
          git config --local user.email "{ID}+{username}@users.noreply.github.com"
          git add translations.tar.gz
          git commit -m "[CI]Update translations" || true
          git push
